#
# This file is part of Edgehog.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Edgehog.Repo.Migrations.AddCampaignScheduledAtTimestamp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Add column without default
    alter table(:campaigns) do
      add :scheduled_at_timestamp, :utc_datetime_usec
    end

    # Backfill existing rows with meaningful logic
    execute("""
    UPDATE campaigns
    SET scheduled_at_timestamp =
      COALESCE(
        start_timestamp,
        inserted_at
      )
    WHERE scheduled_at_timestamp IS NULL
    """)

    # Set default for future inserts
    alter table(:campaigns) do
      modify :scheduled_at_timestamp, :utc_datetime_usec,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:campaigns) do
      remove :scheduled_at_timestamp
    end
  end
end
